const data = {
  info: {
    name: "Bassel Gamal ",
    bio: "I’m a mysterious individual who has yet to fill out my bio. One thing’s for certain: I love coding",
    from: "from Egypt   ",
    age: "2002",
  },
  skills: [
    "html",
    "ts",
    "bs",
    "tilwind",
    "css",
    "git",
    "gh",
    "js",
    "react",
    "nodejs",
    "express",
    "mongodb",
  ],
  works: [
    {
      name: "e-commerce API",
      demo: "https://github.com/DevBassel/e-commerce",
      rebo: "link",
      dis: "e-commerce with nodejs expressjs mongodb and stripe to payment [under development]",
      src: "https://placehold.co/700x400",
      filter: "API",
    },
    {
      name: "Blog App",
      demo: "https://blog-app-msny.onrender.com",
      rebo: "link",
      dis: "Basic blog app with nodejs, reactjs, redux, and mongodb [ friends and chat coming soon ]",
      src: "imgs/projects/project-18.jpg",
      filter: "MERN-APP",
    },
    {
      name: "easybank landing page",
      demo: "https://celebrated-daffodil-89a2a9.netlify.app",
      rebo: "link",
      dis: "landing page with reactjs ",
      src: "imgs/projects/project-20.jpg",
      filter: "react-app",
    },
    {
      name: "todo app",
      demo: "https://stirring-vacherin-b459a8.netlify.app",
      rebo: "link",
      dis: "todo list app with reactjs",
      src: "imgs/projects/project-21.jpg",
      filter: "react-app",
    },
    {
      name: "multi step form",
      demo: "https://fantastic-conkies-d77337.netlify.app",
      rebo: "link",
      dis: "multi step form with reactjs ",
      src: "imgs/projects/project-19.jpg",
      filter: "react-app",
    },
    {
      name: "letters game with keyboard",
      demo: "https://warm-bombolone-038a07.netlify.app/",
      rebo: "link",
      dis: "letters game with HTML, CSS and JavaScript",
      src: "imgs/projects/project-18.png",
      filter: "games",
    },
    {
      name: "memory game",
      demo: "https://devbassel.github.io/memory-game/",
      rebo: "link",
      dis: "Memory game with HTML , CSS and JS",
      src: "imgs/projects/project-16.jpg",
      filter: "games",
    },
    {
      name: "tic tac toe",
      demo: "https://devbassel.github.io/X_O-Game-/",
      rebo: "link",
      dis: "X O Game",
      src: "imgs/projects/project-17.jpg",
      filter: "games",
    },
    {
      name: "test typing speed",
      demo: "https://DevBassel.github.io/test-speed-typeing/",
      rebo: "link",
      dis: "A game to measure typing speed",
      src: "imgs/projects/project-1.jpg",
      filter: "games",
    },

    {
      name: "Quiz App",
      demo: "https://DevBassel.github.io/Quiz-App/",
      dis: "Quiz App",
      src: "imgs/projects/project-13.png",
      filter: "app",
    },

    {
      name: "Stop Watch",
      demo: "https://devbassel.github.io/Stop-Watch/",
      dis: "Stop Watch",
      src: "imgs/projects/project-15.jpg",
      filter: "app",
    },
    {
      name: "landing page Bondi",
      demo: "https://DevBassel.github.io/bonde/",
      rebo: "link",
      dis: "landing page with bootstrap 5",
      src: "imgs/projects/project-3.png",
      filter: "landing-Page",
    },
    {
      name: "rock paper scissors",
      demo: "https://DevBassel.github.io/rock-paper-scissors/",
      rebo: "link",
      dis: "",
      src: "imgs/projects/project-4.png",
      filter: "games",
    },
    {
      name: "count down",
      demo: "https://DevBassel.github.io/Count-Down/",
      rebo: "link",
      dis: "custom count down",
      src: "imgs/projects/project-5.png",
      filter: "app",
    },
    {
      name: "e-commerce product page",
      demo: "https://DevBassel.github.io/E-commerce-product-page/",
      rebo: "link",
      dis: "e-commerce product page",
      src: "imgs/projects/project-6.png",
      filter: "e-commerce",
    },
    // {
    //   name: "slider",
    //   demo: "https://elegant-sinoussi-83d8d4.netlify.app/",
    //   rebo: "link",
    //   dis: "",
    //   src: "imgs/projects/project-7.png",
    //   filter: "app",
    // },
    {
      name: "Kasper Temple",
      demo: "https://DevBassel.github.io/Kasper/",
      dis: "Landing Page",
      src: "imgs/projects/project-8.png",
      filter: "landing-Page",
    },
    {
      name: "fylo-dark-theme-landing-page",
      demo: "https://DevBassel.github.io/fylo-dark-theme-landing-page-master/",
      dis: "Landing page",
      src: "imgs/projects/project-9.png",
      filter: "landing-Page",
    },
    {
      name: "blogr-landing-page",
      demo: "https://DevBassel.github.io/blogr-landing-page-main/",
      dis: "Landing Page",
      src: "imgs/projects/project-10.png",
      filter: "landing-Page",
    },
    {
      name: "bookmark-landing-page",
      demo: "https://DevBassel.github.io/bookmark-landing-page-master/",
      dis: "Landing page",
      src: "imgs/projects/project-11.png",
      filter: "landing-Page",
    },
    {
      name: "random quote",
      demo: "https://DevBassel.github.io/random-Quote/",
      dis: "random quote from api",
      src: "imgs/projects/project-12.png",
      filter: "app",
    },
  ],
  contact: {
    GitHub: "https://github.com/DevBassel?tab=repositories",
    LinkedIn: "https://www.linkedin.com/in/bassel-gamal-ba5897192",
    fb: "https://www.facebook.com/Bassel.Gamal.6",
    codeWars: "https://www.codewars.com/users/Bassel%20gamal",
    email: "mailto:dev.basselgamal@gmail.com",
  },
  themes: {
    theme_1: {
      text: "hsl(150, 100%, 66%)",
      bg: "#124",
      sbg: "hsl(217, 19%, 24%)",
      light: " hsl(193, 38%, 86%)",
    },
    theme_2: {
      text: "#C5DFF8",
      bg: "#4A55A2",
      sbg: "#7895CB",
      light: "#A0BFE0",
    },
  },
};
